global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'instance']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'admin-iris'

receivers:
  - name: 'admin-iris'
    email_configs:
      - to: 'admin@iris-nice.lan'
        from: 'alertmanager@iris-nice.lan'
        smarthost: 'smtp.iris-nice.lan:587'
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
